# Generated by Django 5.2.16 on 2026-08-07 19:43

import datetime

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0002_vehicle"),
        ("personnel", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PersonnelRetentionPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("retention_period", models.DurationField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name="person",
            name="anonymized_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="person",
            name="anonymized_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="anonymized_people",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="departed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="person",
            name="display_name",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="person",
            name="email_verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="person",
            name="email_verified_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="verified_commander_emails",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="first_name",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="person",
            name="incident_commander_eligible",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="person",
            name="incident_commander_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="person",
            name="last_name",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="person",
            name="lifecycle_status",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "Active"),
                    ("DEPARTED", "Departed"),
                    ("ANONYMIZED", "Anonymized"),
                ],
                default="ACTIVE",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="personnel_number",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="person",
            name="retention_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="person",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddConstraint(
            model_name="person",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("lifecycle_status", "ACTIVE"), ("personnel_number__isnull", False)
                ),
                fields=("department", "personnel_number"),
                name="unique_active_personnel_number_per_department",
            ),
        ),
        migrations.AddConstraint(
            model_name="person",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("active", True),
                        ("departed_at__isnull", True),
                        ("lifecycle_status", "ACTIVE"),
                    ),
                    models.Q(
                        ("active", False),
                        ("departed_at__isnull", False),
                        ("lifecycle_status", "DEPARTED"),
                    ),
                    models.Q(
                        ("active", False),
                        ("anonymized_at__isnull", False),
                        ("lifecycle_status", "ANONYMIZED"),
                    ),
                    _connector="OR",
                ),
                name="person_lifecycle_state_consistency",
            ),
        ),
        migrations.AddField(
            model_name="personnelretentionpolicy",
            name="department",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="personnel_retention_policy",
                to="organizations.department",
            ),
        ),
        migrations.AddField(
            model_name="personnelretentionpolicy",
            name="updated_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="updated_personnel_retention_policies",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="personnelretentionpolicy",
            constraint=models.CheckConstraint(
                condition=models.Q(("retention_period__gt", datetime.timedelta(0))),
                name="personnel_retention_period_positive",
            ),
        ),
    ]
