# Generated by Django 5.2.16 on 2026-08-09 14:46

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tablets", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="tablet",
            name="asset_number",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name="tablet",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_tablets",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="tablet",
            name="display_name",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="tablet",
            name="removed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tablet",
            name="removed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="removed_tablets",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="tablet",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("ACTIVE", "Active"),
                    ("STALE", "Stale"),
                    ("REMOVED", "Removed"),
                    ("LOST", "Lost"),
                    ("RETIRED", "Retired"),
                ],
                default="PENDING",
                max_length=16,
            ),
        ),
        migrations.CreateModel(
            name="AdoptionInvitation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("token_hash", models.CharField(max_length=64, unique=True)),
                ("expires_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("failed_attempt_count", models.PositiveSmallIntegerField(default=0)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_adoption_invitations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tablet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="adoption_invitations",
                        to="tablets.tablet",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AppInstallation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("installation_uuid", models.UUIDField(unique=True)),
                ("credential_hash", models.CharField(max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("STALE", "Stale"),
                            ("REVOKED", "Revoked"),
                            ("REPLACED", "Replaced"),
                        ],
                        default="ACTIVE",
                        max_length=16,
                    ),
                ),
                ("app_version", models.CharField(max_length=64)),
                ("hpke_public_key", models.BinaryField()),
                ("hpke_ciphersuite", models.CharField(max_length=128)),
                ("hpke_key_fingerprint", models.CharField(max_length=64)),
                ("hpke_key_verified_at", models.DateTimeField()),
                ("adopted_at", models.DateTimeField()),
                ("last_successful_check_in_at", models.DateTimeField(blank=True, null=True)),
                ("authorization_valid_until", models.DateTimeField()),
                ("stale_at", models.DateTimeField(blank=True, null=True)),
                ("reactivated_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("revocation_reason", models.CharField(blank=True, max_length=512)),
                (
                    "adopted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="adopted_app_installations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reactivated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reactivated_app_installations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tablet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="installations",
                        to="tablets.tablet",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReactivationInvitation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("token_hash", models.CharField(max_length=64, unique=True)),
                ("expires_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("failed_attempt_count", models.PositiveSmallIntegerField(default=0)),
                (
                    "app_installation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reactivation_invitations",
                        to="tablets.appinstallation",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_reactivation_invitations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AdoptionRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("installation_uuid", models.UUIDField()),
                ("app_version", models.CharField(max_length=64)),
                ("hpke_public_key", models.BinaryField()),
                ("hpke_public_key_fingerprint", models.CharField(max_length=64)),
                ("hpke_ciphersuite", models.CharField(max_length=128)),
                ("expected_hmac_digest", models.BinaryField()),
                ("canonical_context_hash", models.CharField(max_length=64)),
                ("encrypted_challenge", models.BinaryField()),
                ("expires_at", models.DateTimeField()),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("failed_attempt_count", models.PositiveSmallIntegerField(default=0)),
                (
                    "invitation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="requests",
                        to="tablets.adoptioninvitation",
                    ),
                ),
                (
                    "reactivation_invitation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="requests",
                        to="tablets.reactivationinvitation",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="appinstallation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status__in", ("ACTIVE", "STALE"))),
                fields=("tablet",),
                name="one_current_installation_per_tablet",
            ),
        ),
        migrations.AddConstraint(
            model_name="adoptionrequest",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("invitation__isnull", False), ("reactivation_invitation__isnull", True)
                    ),
                    models.Q(
                        ("invitation__isnull", True), ("reactivation_invitation__isnull", False)
                    ),
                    _connector="OR",
                ),
                name="adoption_request_has_one_invitation",
            ),
        ),
    ]
