# Generated by Django 5.2.16 on 2026-08-21 19:37

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0005_department_tablet_lease_days"),
        ("tablets", "0003_app_version_tracking_and_completion_recovery"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TabletApiActivity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("occurred_at", models.DateTimeField(db_index=True)),
                ("method", models.CharField(max_length=8)),
                ("path", models.CharField(max_length=256)),
                ("status_code", models.PositiveSmallIntegerField()),
                ("duration_ms", models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                "ordering": ("-occurred_at",),
            },
        ),
        migrations.AlterField(
            model_name="tablet",
            name="display_name",
            field=models.CharField(max_length=255),
        ),
        migrations.AddConstraint(
            model_name="tablet",
            constraint=models.UniqueConstraint(
                fields=("department", "display_name"),
                name="tablet_display_name_unique_per_department",
            ),
        ),
        migrations.AddConstraint(
            model_name="tablet",
            constraint=models.UniqueConstraint(
                condition=models.Q(("asset_number", ""), _negated=True),
                fields=("department", "asset_number"),
                name="tablet_asset_number_unique_per_department",
            ),
        ),
        migrations.AddField(
            model_name="tabletapiactivity",
            name="app_installation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="api_activity",
                to="tablets.appinstallation",
            ),
        ),
        migrations.AddIndex(
            model_name="tabletapiactivity",
            index=models.Index(
                fields=["app_installation", "-occurred_at"], name="tablet_api_act_install_idx"
            ),
        ),
    ]
