# Generated by Django 5.2.16 on 2026-08-23 08:17

from django.db import migrations, models


def _migrate_asset_states(apps, schema_editor):
    """Map legacy physical Tablet states to the Stage 2.1 asset lifecycle.

    PENDING → INACTIVE (provisioning belongs to installations, not the asset)
    STALE   → ACTIVE  (stale is installation health, not the asset state)
    REMOVED stays a legacy tombstone and is deliberately preserved.
    """
    Tablet = apps.get_model("tablets", "Tablet")
    Tablet.objects.filter(status="PENDING").update(status="INACTIVE")
    Tablet.objects.filter(status="STALE").update(status="ACTIVE")


def _noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("tablets", "0004_tabletapiactivity_alter_tablet_display_name_and_more"),
    ]

    operations = [
        migrations.RunPython(_migrate_asset_states, _noop),
        migrations.AlterField(
            model_name="tablet",
            name="status",
            field=models.CharField(
                choices=[
                    ("INACTIVE", "Inactive"),
                    ("ACTIVE", "Active"),
                    ("LOST", "Lost"),
                    ("RETIRED", "Retired"),
                    ("REMOVED", "Removed"),
                ],
                default="INACTIVE",
                max_length=16,
            ),
        ),
    ]
