from django.urls import path

from apps.reference_data import views

urlpatterns = [
    path(
        "departments/<uuid:department_id>/hydrants/", views.hydrants, name="reference-data-hydrants"
    ),
    path(
        "departments/<uuid:department_id>/phonebook/",
        views.phonebook,
        name="reference-data-phonebook",
    ),
    path(
        "departments/<uuid:department_id>/phonebook/duplicates/",
        views.phonebook_duplicate_review,
        name="reference-data-phonebook-duplicates",
    ),
    path(
        "departments/<uuid:department_id>/phonebook/create/",
        views.phonebook_create,
        name="reference-data-phonebook-create",
    ),
    path(
        "phonebook/<uuid:entry_id>/", views.phonebook_detail, name="reference-data-phonebook-detail"
    ),
    path(
        "phonebook/<uuid:entry_id>/edit/",
        views.phonebook_edit_modal,
        name="reference-data-phonebook-edit",
    ),
    path(
        "phonebook/<uuid:entry_id>/delete/",
        views.phonebook_delete_modal,
        name="reference-data-phonebook-delete",
    ),
    path(
        "departments/<uuid:department_id>/hydrants/create/",
        views.hydrant_create,
        name="reference-data-hydrant-create",
    ),
    path("hydrants/<uuid:hydrant_id>/", views.hydrant_manage, name="reference-data-hydrant-manage"),
    path(
        "hydrants/<uuid:hydrant_id>/edit/",
        views.hydrant_edit_modal,
        name="reference-data-hydrant-edit",
    ),
    path(
        "hydrants/<uuid:hydrant_id>/lifecycle/",
        views.hydrant_lifecycle,
        name="reference-data-hydrant-lifecycle",
    ),
    path(
        "hydrants/<uuid:hydrant_id>/delete/",
        views.hydrant_delete_modal,
        name="reference-data-hydrant-delete",
    ),
    path(
        "departments/<uuid:department_id>/fire-plans/",
        views.fire_plans,
        name="reference-data-fire-plans",
    ),
    path(
        "departments/<uuid:department_id>/klgv-plans/",
        views.klgv_plans,
        name="reference-data-klgv-plans",
    ),
    path(
        "fire-plans/<uuid:fire_plan_id>/",
        views.fire_plan_detail,
        name="reference-data-fire-plan-detail",
    ),
    path(
        "fire-plans/<uuid:fire_plan_id>/edit/",
        views.fire_plan_edit_modal,
        name="reference-data-fire-plan-edit",
    ),
    path(
        "fire-plans/<uuid:fire_plan_id>/lifecycle/",
        views.fire_plan_lifecycle,
        name="reference-data-fire-plan-lifecycle",
    ),
    path(
        "fire-plans/<uuid:fire_plan_id>/delete/",
        views.fire_plan_delete_modal,
        name="reference-data-fire-plan-delete",
    ),
    path(
        "klgv-plans/<uuid:klgv_plan_id>/",
        views.klgv_plan_detail,
        name="reference-data-klgv-plan-detail",
    ),
    path(
        "klgv-plans/<uuid:klgv_plan_id>/edit/",
        views.klgv_plan_edit_modal,
        name="reference-data-klgv-plan-edit",
    ),
    path(
        "klgv-plans/<uuid:klgv_plan_id>/lifecycle/",
        views.klgv_plan_lifecycle,
        name="reference-data-klgv-plan-lifecycle",
    ),
    path(
        "klgv-plans/<uuid:klgv_plan_id>/delete/",
        views.klgv_plan_delete_modal,
        name="reference-data-klgv-plan-delete",
    ),
]
