d /run/fire-backend 0750 fire_backend www-data -
d /var/lib/fire-backend 0750 fire_backend fire_backend -
d /var/lib/fire-backend/static 0750 fire_backend fire_backend -
d /var/lib/fire-backend/quarantine 0750 fire_backend fire_pdf_sanitizer -
d /var/lib/fire-backend/sanitizer-output 0750 fire_backend fire_pdf_sanitizer -
d /var/lib/fire-backend/fire-plans 0750 fire_backend fire_backend -
d /var/lib/fire-backend/publications 0750 fire_publication fire_publication -
d /var/lib/fire-backend/publications-tmp 0750 fire_publication fire_publication -
