d /run/fire-backend 0750 fire_backend www-data -
d /var/lib/fire-backend 0710 fire_backend fire_nginx -
d /var/lib/fire-backend/static 0755 root root -
d /var/lib/fire-backend/quarantine 2710 fire_backend fire_pdf_sanitizer -
d /var/lib/fire-backend/sanitizer-output 2710 fire_backend fire_pdf_sanitizer -
d /var/lib/fire-backend/fire-plans 0750 fire_backend fire_backend -
d /var/lib/fire-backend/publications 2750 fire_publication fire_nginx -
d /var/lib/fire-backend/publications-tmp 0700 fire_publication fire_publication -
