# Generated by Django 5.1.2 on 2026-08-25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("publications", "0011_department_klgv_plans_registry")]

    operations = [
        migrations.AlterField(
            model_name="datasetpublication",
            name="status",
            field=models.CharField(
                choices=[
                    ("STAGED", "Staged"),
                    ("BUILDING", "Building"),
                    ("READY_FOR_REVIEW", "Ready for review"),
                    ("PUBLISHED", "Published"),
                    ("FAILED", "Failed"),
                    ("SUPERSEDED", "Superseded"),
                    ("REJECTED", "Rejected"),
                    ("OBSOLETE", "Obsolete"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="BUILDING",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="publicationjob",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("RUNNING", "Running"),
                    ("SUCCEEDED", "Succeeded"),
                    ("FAILED", "Failed"),
                    ("OBSOLETE", "Obsolete"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="PENDING",
                max_length=10,
            ),
        ),
    ]
