# Generated by Django 5.1.2 on 2026-08-26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("publications", "0012_publication_lifecycle_states")]

    operations = [
        migrations.AddField(
            model_name="datasetpublication",
            name="source_fingerprint",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
    ]
