# Generated by Django 5.1.2 on 2026-08-26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("publications", "0013_datasetpublication_source_fingerprint")]

    operations = [
        migrations.AddField(
            model_name="datasetpublication",
            name="source_snapshot",
            field=models.JSONField(default=dict),
        ),
    ]
