# Generated by Django 5.2.16 on 2026-08-26 19:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("publications", "0014_datasetpublication_source_snapshot"),
    ]

    operations = [
        migrations.AddField(
            model_name="datasetscopestate",
            name="current_source_fingerprint",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
    ]
