# Generated by Django 5.2.16 on 2026-08-27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("publications", "0015_current_source_fingerprint")]

    operations = [
        migrations.AlterField(
            model_name="datasetpublication",
            name="source_snapshot",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="datasetpublication",
            index=models.Index(
                fields=["status", "scope_state", "-version_number"],
                name="pub_status_scope_ver_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="datasetpublication",
            index=models.Index(fields=["status", "created_at"], name="pub_status_created_idx"),
        ),
    ]
