# Generated by Django 5.2.16 on 2026-08-28 20:00

import uuid

import django.db.models.deletion
from django.db import migrations, models


def install_document_artifact_guards(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    schema_editor.execute("""
        CREATE OR REPLACE FUNCTION publications_guard_fire_plan_document_artifact()
        RETURNS trigger AS $$
        BEGIN
          IF NEW IS DISTINCT FROM OLD THEN
            RAISE EXCEPTION 'Fire Plan document artifacts are immutable';
          END IF;
          RETURN NEW;
        END; $$ LANGUAGE plpgsql;

        CREATE TRIGGER publications_fire_plan_document_artifact_immutable
        BEFORE UPDATE ON publications_fireplandocumentartifact
        FOR EACH ROW EXECUTE FUNCTION publications_guard_fire_plan_document_artifact();

        CREATE OR REPLACE FUNCTION publications_guard_fire_plan_artifact_reference()
        RETURNS trigger AS $$
        DECLARE
          artifact_plan uuid;
          publication_department uuid;
          plan_department uuid;
        BEGIN
          IF TG_OP <> 'INSERT' THEN
            RAISE EXCEPTION 'Publication Fire Plan artifact references are immutable';
          END IF;
          SELECT fire_plan_id INTO artifact_plan
            FROM publications_fireplandocumentartifact WHERE id = NEW.document_artifact_id;
          SELECT department_id INTO publication_department
            FROM publications_datasetpublication WHERE id = NEW.publication_id;
          SELECT department_id INTO plan_department
            FROM reference_data_fireplan WHERE id = NEW.fire_plan_id;
          IF artifact_plan IS NULL OR artifact_plan <> NEW.fire_plan_id THEN
            RAISE EXCEPTION 'Document artifact must belong to referenced Fire Plan';
          END IF;
          IF publication_department IS NULL OR plan_department IS NULL
             OR publication_department <> plan_department THEN
            RAISE EXCEPTION 'Fire Plan must belong to publication department';
          END IF;
          RETURN NEW;
        END; $$ LANGUAGE plpgsql;

        CREATE TRIGGER publications_fire_plan_artifact_reference_guard
        BEFORE INSERT OR UPDATE OR DELETE ON publications_publicationfireplanartifactreference
        FOR EACH ROW EXECUTE FUNCTION publications_guard_fire_plan_artifact_reference();
    """)


def remove_document_artifact_guards(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    schema_editor.execute("""
        DROP TRIGGER IF EXISTS publications_fire_plan_document_artifact_immutable
          ON publications_fireplandocumentartifact;
        DROP TRIGGER IF EXISTS publications_fire_plan_artifact_reference_guard
          ON publications_publicationfireplanartifactreference;
        DROP FUNCTION IF EXISTS publications_guard_fire_plan_document_artifact();
        DROP FUNCTION IF EXISTS publications_guard_fire_plan_artifact_reference();
    """)


class Migration(migrations.Migration):
    dependencies = [
        ("publications", "0016_publication_retention"),
        ("reference_data", "0013_hydrant_descriptive_location"),
    ]

    operations = [
        migrations.CreateModel(
            name="FirePlanDocumentArtifact",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("sanitized_pdf_sha256", models.CharField(max_length=64)),
                ("artifact_path", models.CharField(max_length=512, unique=True)),
                ("ciphertext_size", models.PositiveBigIntegerField()),
                ("ciphertext_sha256", models.CharField(max_length=64)),
                ("nonce", models.BinaryField()),
                ("wrapped_cek", models.BinaryField()),
                ("encryption_algorithm", models.CharField(max_length=32)),
                ("wrapping_algorithm", models.CharField(max_length=32)),
                ("kek_version", models.CharField(max_length=64)),
                ("signature", models.BinaryField()),
                ("signature_algorithm", models.CharField(max_length=32)),
                ("signing_key_version", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "fire_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="document_artifacts",
                        to="reference_data.fireplan",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PublicationFirePlanArtifactReference",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "document_artifact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="publication_references",
                        to="publications.fireplandocumentartifact",
                    ),
                ),
                (
                    "fire_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="publication_artifact_references",
                        to="reference_data.fireplan",
                    ),
                ),
                (
                    "publication",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fire_plan_artifact_references",
                        to="publications.datasetpublication",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="fireplandocumentartifact",
            index=models.Index(
                fields=["fire_plan", "created_at"], name="doc_artifact_plan_created_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="fireplandocumentartifact",
            constraint=models.UniqueConstraint(
                fields=("fire_plan", "sanitized_pdf_sha256"),
                name="unique_fire_plan_document_artifact_content",
            ),
        ),
        migrations.AddConstraint(
            model_name="publicationfireplanartifactreference",
            constraint=models.UniqueConstraint(
                fields=("publication", "fire_plan"),
                name="unique_publication_fire_plan_artifact_reference",
            ),
        ),
        migrations.RunPython(install_document_artifact_guards, remove_document_artifact_guards),
    ]
