# Generated by Django 5.2.16 on 2026-08-28 20:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0017_fire_plan_document_artifacts'),
        ('tablets', '0008_remove_obsolete_reactivation_flow'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirePlanGenerationKey',
            fields=[
                ('publication', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='fire_plan_generation_key', serialize=False, to='publications.datasetpublication')),
                ('wrapped_key', models.BinaryField()),
                ('wrapping_algorithm', models.CharField(max_length=32)),
                ('kek_version', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FirePlanGenerationManifest',
            fields=[
                ('publication', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='fire_plan_generation_manifest', serialize=False, to='publications.datasetpublication')),
                ('payload', models.JSONField(default=dict)),
                ('signature', models.BinaryField()),
                ('signature_algorithm', models.CharField(max_length=32)),
                ('signing_key_version', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FirePlanGenerationKeyGrant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('READY', 'Ready'), ('FAILED', 'Failed'), ('REVOKED', 'Revoked')], default='PENDING', max_length=12)),
                ('hpke_ciphersuite', models.CharField(blank=True, max_length=128)),
                ('hpke_encapsulated_key', models.BinaryField(blank=True, null=True)),
                ('hpke_wrapped_generation_key', models.BinaryField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.CharField(blank=True, max_length=512)),
                ('app_installation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fire_plan_generation_key_grants', to='tablets.appinstallation')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fire_plan_generation_key_grants', to='publications.datasetpublication')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('publication', 'app_installation'), name='unique_fire_plan_generation_key_grant')],
            },
        ),
    ]
