# Generated by Django 5.2.16 on 2026-08-28

import uuid

from django.db import migrations, models


def allow_terminal_reference_release(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    schema_editor.execute("""
        CREATE OR REPLACE FUNCTION publications_guard_fire_plan_artifact_reference()
        RETURNS trigger AS $$
        DECLARE
          artifact_plan uuid;
          publication_department uuid;
          plan_department uuid;
          publication_status varchar;
        BEGIN
          IF TG_OP = 'DELETE' THEN
            SELECT status INTO publication_status
              FROM publications_datasetpublication WHERE id = OLD.publication_id;
            IF publication_status NOT IN ('FAILED', 'CANCELLED', 'REJECTED', 'OBSOLETE') THEN
              RAISE EXCEPTION 'Only terminal publication references can be released';
            END IF;
            RETURN OLD;
          END IF;
          IF TG_OP <> 'INSERT' THEN
            RAISE EXCEPTION 'Publication Fire Plan artifact references are immutable';
          END IF;
          SELECT fire_plan_id INTO artifact_plan
            FROM publications_fireplandocumentartifact WHERE id = NEW.document_artifact_id;
          SELECT department_id INTO publication_department
            FROM publications_datasetpublication WHERE id = NEW.publication_id;
          SELECT department_id INTO plan_department
            FROM reference_data_fireplan WHERE id = NEW.fire_plan_id;
          IF artifact_plan IS NULL OR artifact_plan <> NEW.fire_plan_id THEN
            RAISE EXCEPTION 'Document artifact must belong to referenced Fire Plan';
          END IF;
          IF publication_department IS NULL OR plan_department IS NULL
             OR publication_department <> plan_department THEN
            RAISE EXCEPTION 'Fire Plan must belong to publication department';
          END IF;
          RETURN NEW;
        END; $$ LANGUAGE plpgsql;
    """)


def restore_immutable_references(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    schema_editor.execute("""
        CREATE OR REPLACE FUNCTION publications_guard_fire_plan_artifact_reference()
        RETURNS trigger AS $$
        DECLARE
          artifact_plan uuid;
          publication_department uuid;
          plan_department uuid;
        BEGIN
          IF TG_OP <> 'INSERT' THEN
            RAISE EXCEPTION 'Publication Fire Plan artifact references are immutable';
          END IF;
          SELECT fire_plan_id INTO artifact_plan
            FROM publications_fireplandocumentartifact WHERE id = NEW.document_artifact_id;
          SELECT department_id INTO publication_department
            FROM publications_datasetpublication WHERE id = NEW.publication_id;
          SELECT department_id INTO plan_department
            FROM reference_data_fireplan WHERE id = NEW.fire_plan_id;
          IF artifact_plan IS NULL OR artifact_plan <> NEW.fire_plan_id THEN
            RAISE EXCEPTION 'Document artifact must belong to referenced Fire Plan';
          END IF;
          IF publication_department IS NULL OR plan_department IS NULL
             OR publication_department <> plan_department THEN
            RAISE EXCEPTION 'Fire Plan must belong to publication department';
          END IF;
          RETURN NEW;
        END; $$ LANGUAGE plpgsql;
    """)


class Migration(migrations.Migration):
    dependencies = [("publications", "0018_fire_plan_v2_delivery")]

    operations = [
        migrations.CreateModel(
            name="FirePlanDocumentArtifactCleanup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("artifact_id", models.UUIDField(unique=True)),
                ("artifact_path", models.CharField(max_length=512, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RunPython(allow_terminal_reference_release, restore_immutable_references),
    ]
