# Generated by Django 5.2.16 on 2026-08-28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("publications", "0019_fire_plan_document_artifact_cleanup")]

    operations = [
        migrations.AddField(
            model_name="datasetscopestate",
            name="delivery_format",
            field=models.CharField(
                choices=[
                    ("V1_ARTIFACT", "V1 artifact"),
                    ("DOCUMENT_MANIFEST_V2", "Document manifest v2"),
                ],
                default="V1_ARTIFACT",
                max_length=32,
            ),
        )
    ]
