# Generated by Django 5.2.16 on 2026-08-29 11:05

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0020_fire_plan_document_manifest_cutover'),
        ('tablets', '0008_remove_obsolete_reactivation_flow'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentGenerationKey',
            fields=[
                ('publication', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='document_generation_key', serialize=False, to='publications.datasetpublication')),
                ('wrapped_key', models.BinaryField()),
                ('wrapping_algorithm', models.CharField(max_length=32)),
                ('kek_version', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentGenerationManifest',
            fields=[
                ('publication', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='document_generation_manifest', serialize=False, to='publications.datasetpublication')),
                ('payload', models.JSONField(default=dict)),
                ('signature', models.BinaryField()),
                ('signature_algorithm', models.CharField(max_length=32)),
                ('signing_key_version', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentArtifact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dataset_type_code', models.CharField(max_length=100)),
                ('canonical_document_id', models.UUIDField()),
                ('sanitized_pdf_sha256', models.CharField(max_length=64)),
                ('artifact_path', models.CharField(max_length=512, unique=True)),
                ('ciphertext_size', models.PositiveBigIntegerField()),
                ('ciphertext_sha256', models.CharField(max_length=64)),
                ('nonce', models.BinaryField()),
                ('wrapped_cek', models.BinaryField()),
                ('encryption_algorithm', models.CharField(max_length=32)),
                ('wrapping_algorithm', models.CharField(max_length=32)),
                ('kek_version', models.CharField(max_length=64)),
                ('signature', models.BinaryField()),
                ('signature_algorithm', models.CharField(max_length=32)),
                ('signing_key_version', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['dataset_type_code', 'canonical_document_id', 'created_at'], name='doc_artifact_canon_created_idx')],
                'constraints': [models.UniqueConstraint(fields=('dataset_type_code', 'canonical_document_id', 'sanitized_pdf_sha256'), name='unique_document_artifact_canonical_content')],
            },
        ),
        migrations.CreateModel(
            name='DocumentGenerationKeyGrant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('READY', 'Ready'), ('FAILED', 'Failed'), ('REVOKED', 'Revoked')], default='PENDING', max_length=12)),
                ('hpke_ciphersuite', models.CharField(blank=True, max_length=128)),
                ('hpke_encapsulated_key', models.BinaryField(blank=True, null=True)),
                ('hpke_wrapped_generation_key', models.BinaryField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.CharField(blank=True, max_length=512)),
                ('app_installation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='document_generation_key_grants', to='tablets.appinstallation')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='document_generation_key_grants', to='publications.datasetpublication')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('publication', 'app_installation'), name='unique_document_generation_key_grant')],
            },
        ),
        migrations.CreateModel(
            name='PublicationDocumentArtifactReference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('canonical_document_id', models.UUIDField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document_artifact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='publication_references', to='publications.documentartifact')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='document_artifact_references', to='publications.datasetpublication')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('publication', 'canonical_document_id'), name='unique_publication_document_artifact_reference')],
            },
        ),
    ]
