# Generated by Django 5.2.16 on 2026-09-03 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0025_promote_klgv_document_v2_registry'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='datasetsourcerevision',
            new_name='pub_src_scope_rev_idx',
            old_name='publications_scope_s_631ca6_idx',
        ),
    ]
