# Generated by Django 5.2.16 on 2026-08-09 09:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("reference_data", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="fireplan",
            new_name="reference_d_departm_f01f3d_idx",
            old_name="reference_d_departm_3ca664_idx",
        ),
        migrations.RenameIndex(
            model_name="hydrant",
            new_name="reference_d_departm_8bffe7_idx",
            old_name="reference_d_departm_e48c4a_idx",
        ),
    ]
