# Generated by Django 5.2.16 on 2026-08-09 18:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0004_remove_station_address"),
        ("reference_data", "0004_hydrant_enum_diameter"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="hydrant",
            name="reference_d_departm_8bffe7_idx",
        ),
        migrations.AlterField(
            model_name="hydrant",
            name="status",
            field=models.CharField(blank=True, default="ACTIVE", max_length=128),
        ),
        migrations.AddIndex(
            model_name="hydrant",
            index=models.Index(
                fields=["department", "status"], name="reference_d_departm_8b06cf_idx"
            ),
        ),
    ]
