# Generated by Django 5.2.16 on 2026-08-16 13:59

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0005_department_tablet_lease_days"),
        ("reference_data", "0005_remove_hydrant_reference_d_departm_8bffe7_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="KlgvPlan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("external_identifier", models.CharField(max_length=255)),
                ("title", models.CharField(max_length=255)),
                ("category", models.CharField(blank=True, max_length=128)),
                ("document_key", models.CharField(max_length=255, unique=True)),
                ("original_filename", models.CharField(max_length=255)),
                ("file_size", models.PositiveBigIntegerField()),
                ("page_count", models.PositiveIntegerField()),
                ("source_pdf_sha256", models.CharField(max_length=64)),
                ("sanitized_pdf_sha256", models.CharField(max_length=64)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name="fireplan",
            name="external_identifier",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="fireplan",
            name="source_pdf_sha256",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddConstraint(
            model_name="fireplan",
            constraint=models.UniqueConstraint(
                condition=models.Q(("external_identifier", ""), _negated=True),
                fields=("department", "external_identifier"),
                name="unique_fire_plan_external_identifier_per_department",
            ),
        ),
        migrations.AddField(
            model_name="klgvplan",
            name="department",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="klgv_plans",
                to="organizations.department",
            ),
        ),
        migrations.AddField(
            model_name="klgvplan",
            name="uploaded_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="uploaded_klgv_plans",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="klgvplan",
            index=models.Index(
                fields=["department", "active"], name="reference_d_departm_d8fcbf_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="klgvplan",
            constraint=models.UniqueConstraint(
                fields=("department", "external_identifier"),
                name="unique_klgv_plan_external_identifier_per_department",
            ),
        ),
    ]
