# Generated by Django 5.2.16 on 2026-08-16 14:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reference_data", "0006_workstream4_canonical_ingestion"),
    ]

    operations = [
        migrations.AddField(
            model_name="fireplan",
            name="city",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="fireplan",
            name="postal_code",
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
