# Generated by Django 5.2.16 on 2026-08-18 15:48

from django.conf import settings
from django.db import migrations, models


def validate_existing_fire_plan_identities(apps, schema_editor):
    FirePlan = apps.get_model("reference_data", "FirePlan")
    missing_identity = FirePlan.objects.filter(external_identifier="", address="").exists()
    duplicate_address_identity = (
        FirePlan.objects.filter(external_identifier="", address__gt="")
        .values("department_id", "address")
        .annotate(count=models.Count("id"))
        .filter(count__gt=1)
        .exists()
    )
    if missing_identity or duplicate_address_identity:
        raise RuntimeError(
            "FirePlan identity migration requires manual curation: every existing row needs "
            "an external identifier or address, and blank-external-identifier addresses must "
            "be unique within a department."
        )


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0005_department_tablet_lease_days"),
        ("reference_data", "0007_fire_plan_location_metadata"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(validate_existing_fire_plan_identities, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="fireplan",
            name="object_reference",
        ),
        migrations.AlterField(
            model_name="fireplan",
            name="object_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddConstraint(
            model_name="fireplan",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("external_identifier", ""), _negated=True),
                    models.Q(("address", ""), _negated=True),
                    _connector="OR",
                ),
                name="fire_plan_requires_external_identifier_or_address",
            ),
        ),
        migrations.AddConstraint(
            model_name="fireplan",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("external_identifier", ""), models.Q(("address", ""), _negated=True)
                ),
                fields=("department", "address"),
                name="unique_fire_plan_address_identity_per_department",
            ),
        ),
    ]
