# Generated by Django 5.2.16 on 2026-08-23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("reference_data", "0008_align_fire_plan_identity")]

    operations = [
        migrations.AddField(
            model_name="fireplan",
            name="fsd_location",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="fireplan",
            name="bmz_location",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="fireplan",
            name="rwa_info",
            field=models.TextField(blank=True),
        ),
    ]
