# Generated by Django 5.2.16 on 2026-08-24

from django.contrib.gis.db.models import fields as gis_fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("reference_data", "0010_phase2_hydrant_address")]

    operations = [
        migrations.RenameField(model_name="klgvplan", old_name="title", new_name="object_name"),
        migrations.RenameField(model_name="klgvplan", old_name="document_key", new_name="path"),
        migrations.RenameField(
            model_name="klgvplan", old_name="sanitized_pdf_sha256", new_name="sha256"
        ),
        migrations.AlterField(
            model_name="klgvplan",
            name="external_identifier",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.RemoveConstraint(
            model_name="klgvplan", name="unique_klgv_plan_external_identifier_per_department"
        ),
        migrations.AddField(
            model_name="klgvplan",
            name="address",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="klgvplan",
            name="postal_code",
            field=models.CharField(default="", max_length=32),
        ),
        migrations.AddField(
            model_name="klgvplan", name="city", field=models.CharField(default="", max_length=255)
        ),
        migrations.AddField(
            model_name="klgvplan",
            name="location",
            field=gis_fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.RemoveField(model_name="klgvplan", name="category"),
        migrations.AddConstraint(
            model_name="klgvplan",
            constraint=models.UniqueConstraint(
                condition=~models.Q(external_identifier=""),
                fields=("department", "external_identifier"),
                name="unique_klgv_plan_external_identifier_per_department",
            ),
        ),
    ]
