# Generated by Django 5.2.16 on 2026-08-24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("reference_data", "0011_phase2_klgv_canonical_metadata")]

    operations = [
        migrations.AlterField(
            model_name="klgvplan", name="address", field=models.CharField(max_length=255)
        ),
        migrations.AlterField(
            model_name="klgvplan", name="postal_code", field=models.CharField(max_length=32)
        ),
        migrations.AlterField(
            model_name="klgvplan", name="city", field=models.CharField(max_length=255)
        ),
    ]
