# Generated by Django 5.2.16 on 2026-08-16 13:59

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("organizations", "0005_department_tablet_lease_days"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ImportBatch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "domain",
                    models.CharField(
                        choices=[
                            ("hydrants", "Hydrants"),
                            ("personnel", "Personnel"),
                            ("fire_plans", "Fire plans"),
                            ("klgv_plans", "KLGV plans"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "import_format",
                    models.CharField(
                        choices=[
                            ("csv", "CSV"),
                            ("json", "JSON"),
                            ("geojson", "GeoJSON"),
                            ("pdf", "PDF"),
                            ("zip", "ZIP"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "import_mode",
                    models.CharField(
                        choices=[
                            ("merge", "Merge"),
                            ("authoritative_snapshot", "Authoritative snapshot"),
                            ("upsert", "Upsert"),
                        ],
                        max_length=32,
                    ),
                ),
                ("original_filename", models.CharField(max_length=255)),
                ("upload_sha256", models.CharField(max_length=64)),
                ("staging_key", models.CharField(max_length=255, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("UPLOADED", "Uploaded"),
                            ("PREVIEW_READY", "Preview ready"),
                            ("INVALID", "Invalid"),
                            ("APPLIED", "Applied"),
                            ("CANCELLED", "Cancelled"),
                            ("EXPIRED", "Expired"),
                            ("FAILED", "Failed"),
                        ],
                        default="UPLOADED",
                        max_length=16,
                    ),
                ),
                ("baseline", models.JSONField(default=dict)),
                ("normalized_intent", models.JSONField(default=dict)),
                ("validation_errors", models.JSONField(default=list)),
                ("validation_summary", models.JSONField(default=dict)),
                ("add_count", models.PositiveIntegerField(default=0)),
                ("update_count", models.PositiveIntegerField(default=0)),
                ("deactivate_count", models.PositiveIntegerField(default=0)),
                ("unchanged_count", models.PositiveIntegerField(default=0)),
                ("affected_scopes", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("previewed_at", models.DateTimeField(blank=True, null=True)),
                ("applied_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("failed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="import_batches",
                        to="organizations.department",
                    ),
                ),
                (
                    "station",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="organizations.station",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["department", "status", "created_at"],
                        name="ingestion_i_departm_44a227_idx",
                    )
                ],
            },
        ),
    ]
