# Generated by Django 5.2.16 on 2026-08-24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("ingestion", "0001_workstream4_canonical_ingestion")]

    operations = [
        migrations.AlterField(
            model_name="importbatch",
            name="domain",
            field=models.CharField(
                choices=[
                    ("hydrants", "Hydrants"),
                    ("personnel", "Personnel"),
                    ("fire_plans", "Fire plans"),
                    ("klgv_plans", "KLGV plans"),
                    ("station_vehicles", "Stations and vehicles"),
                ],
                max_length=32,
            ),
        )
    ]
