# Generated by Django 5.2.16 on 2026-09-10 17:31

import uuid

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0007_department_locale_and_timezone"),
        ("outbound_mail", "0002_systemmailconfiguration_last_verification_code_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DepartmentRecipientPolicy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("restriction_enabled", models.BooleanField(default=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "department",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="mail_recipient_policy",
                        to="organizations.department",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="updated_department_mail_recipient_policies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DepartmentMailConfiguration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "delivery_mode",
                    models.CharField(
                        choices=[
                            ("DISABLED", "Disabled"),
                            ("SYSTEM", "System managed"),
                            ("CUSTOM_SMTP", "Custom SMTP"),
                        ],
                        default="DISABLED",
                        max_length=16,
                    ),
                ),
                ("smtp_host", models.CharField(blank=True, default="", max_length=255)),
                (
                    "smtp_port",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(65535),
                        ],
                    ),
                ),
                (
                    "smtp_tls_mode",
                    models.CharField(
                        blank=True,
                        choices=[("STARTTLS", "STARTTLS"), ("IMPLICIT_TLS", "Implicit TLS")],
                        default="",
                        max_length=16,
                    ),
                ),
                ("smtp_sender_name", models.CharField(blank=True, default="", max_length=255)),
                (
                    "smtp_sender_email",
                    models.EmailField(
                        blank=True,
                        default="",
                        max_length=254,
                        validators=[
                            django.core.validators.EmailValidator(
                                message="A valid sender email address is required."
                            )
                        ],
                    ),
                ),
                ("smtp_username", models.CharField(blank=True, default="", max_length=255)),
                (
                    "smtp_password_encrypted",
                    models.CharField(blank=True, default="", editable=False, max_length=4096),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "department",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="mail_configuration",
                        to="organizations.department",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="updated_department_mail_configurations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("smtp_password_encrypted", ""), ("smtp_username", "")),
                            models.Q(
                                ("smtp_username__gt", ""), ("smtp_password_encrypted__gt", "")
                            ),
                            _connector="OR",
                        ),
                        name="department_mail_smtp_auth_pair",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="DepartmentRecipientDomain",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("domain", models.CharField(max_length=253)),
                (
                    "policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approved_domains",
                        to="outbound_mail.departmentrecipientpolicy",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("policy", "domain"), name="unique_department_mail_domain"
                    )
                ],
            },
        ),
    ]
