# Generated by Django 5.2.16 on 2026-09-10 17:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("outbound_mail", "0003_departmentrecipientpolicy_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="departmentmailconfiguration",
            name="last_smtp_verification_code",
            field=models.CharField(blank=True, default="", editable=False, max_length=64),
        ),
        migrations.AddField(
            model_name="departmentmailconfiguration",
            name="last_smtp_verification_outcome",
            field=models.CharField(blank=True, default="", editable=False, max_length=16),
        ),
        migrations.AddField(
            model_name="departmentmailconfiguration",
            name="last_smtp_verified_at",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
