# Generated by Django 5.2.16 on 2026-09-10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("outbound_mail", "0005_tabletreportdeliveryrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemmailconfiguration",
            name="outbound_mail_https_proxy",
            field=models.CharField(blank=True, default=None, max_length=2048, null=True),
        ),
    ]
