# Generated by Django 5.2.16 on 2026-08-07 19:19

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("organizations", "0002_vehicle"),
        ("personnel", "0001_initial"),
        ("tablets", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PersonnelStationAssignment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "assignment_type",
                    models.CharField(
                        choices=[("HOME", "Home"), ("TEMPORARY", "Temporary")], max_length=16
                    ),
                ),
                ("valid_from", models.DateTimeField()),
                ("valid_until", models.DateTimeField(blank=True, null=True)),
                ("reason", models.CharField(blank=True, max_length=512)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_personnel_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ended_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ended_personnel_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="station_assignments",
                        to="personnel.person",
                    ),
                ),
                (
                    "station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="personnel_assignments",
                        to="organizations.station",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("assignment_type", "HOME"),
                            ("ended_at__isnull", True),
                            ("valid_until__isnull", True),
                        ),
                        fields=("person",),
                        name="one_open_home_assignment_per_person",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("valid_until__isnull", True),
                            ("valid_until__gt", models.F("valid_from")),
                            _connector="OR",
                        ),
                        name="personnel_assignment_valid_window",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="TabletVehicleAssignment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("valid_from", models.DateTimeField()),
                ("valid_until", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("reason", models.CharField(blank=True, max_length=512)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_tablet_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ended_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ended_tablet_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tablet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vehicle_assignments",
                        to="tablets.tablet",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tablet_assignments",
                        to="organizations.vehicle",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("ended_at__isnull", True), ("valid_until__isnull", True)
                        ),
                        fields=("tablet",),
                        name="one_open_vehicle_assignment_per_tablet",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("valid_until__isnull", True),
                            ("valid_until__gt", models.F("valid_from")),
                            _connector="OR",
                        ),
                        name="tablet_assignment_valid_window",
                    ),
                ],
            },
        ),
    ]
