#!/usr/bin/env bash
# Focused deployment regression tests for application-secret KEK provisioning.
set -Euo pipefail

SELF_DIR=$(CDPATH= cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)
ROOT=$(CDPATH= cd -- "$SELF_DIR/../.." && pwd)
LIB_DIR="$ROOT/deploy/lib"
TMPROOT=$(mktemp -d)
trap 'rm -rf "$TMPROOT"' EXIT

export FIREDASH_ETC="$TMPROOT/etc/fire-backend"
export PYTHONPATH="$TMPROOT/release${PYTHONPATH:+:$PYTHONPATH}"
mkdir -p "$FIREDASH_ETC/credentials" "$TMPROOT/release/venv/bin"
ln -s "$ROOT/apps" "$TMPROOT/release/apps"

# Production calls the release venv.  This wrapper makes the test portable while
# still importing the release's application-secret runtime implementation.
cat > "$TMPROOT/release/venv/bin/python" <<'EOF'
#!/usr/bin/env bash
exec "${FIREDASH_TEST_PYTHON:-python3}" "$@"
EOF
chmod +x "$TMPROOT/release/venv/bin/python"

# shellcheck source=../lib/common.sh
source "$LIB_DIR/common.sh"
# shellcheck source=../lib/secrets.sh
source "$LIB_DIR/secrets.sh"

# The test sandbox has no production group; retain atomic byte semantics.
install_file_atomic() {
    local src=$1 dst=$2
    local tmp
    tmp=$(mktemp "${dst}.tmp.XXXXXX")
    cat "$src" > "$tmp"
    chmod 0600 "$tmp"
    mv -f "$tmp" "$dst"
}

failures=0
fail() { echo "FAIL: $*" >&2; failures=$((failures + 1)); }
credential="$SECRET_DIR/application-secret-kek-ring.json"

# Set up the other established-install credentials, but deliberately omit the
# new ring to model an upgrade from a pre-mail FireDash release.
printf '%064d' 0 > "$SECRET_DIR/database-owner-password"
printf '%064d' 0 > "$SECRET_DIR/backup-role-password"
head -c 32 /dev/zero > "$SECRET_DIR/publication-kek"
"$TMPROOT/release/venv/bin/python" - "$SECRET_DIR/publication-signing-key" \
    "$SECRET_DIR/publication-signing-public-key" <<'PY'
import sys
from pathlib import Path
from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PrivateKey

seed = b"s" * 32
Path(sys.argv[1]).write_bytes(seed)
Path(sys.argv[2]).write_bytes(
    Ed25519PrivateKey.from_private_bytes(seed).public_key().public_bytes_raw()
)
PY
cat > "$ENV_FILE" <<'EOF'
POSTGRES_PASSWORD=0000000000000000000000000000000000000000000000000000000000000000
DJANGO_SECRET_KEY=test-secret
APPLICATION_SECRET_KEK_VERSION=1
EOF

# A pre-feature established install has no ring. Its real validation path must
# provision one, then the exact generated bytes must load through the runtime
# parser/cipher.
validate_established_secrets "$TMPROOT/release" || fail "established upgrade did not provision missing ring"
[[ -f $credential ]] || fail "initial ring was not created"
"$TMPROOT/release/venv/bin/python" - "$credential" <<'PY' || fail "generated ring is not runtime-valid"
import sys
from pathlib import Path
from apps.application_secrets.crypto import load_application_secret_keyring

assert load_application_secret_keyring(Path(sys.argv[1]), active_version="1").active_version == "1"
PY

# A subsequent deployment must not replace a valid KEK ring.
before=$(sha256sum "$credential" | awk '{print $1}')
ensure_application_secret_keyring "$TMPROOT/release" || fail "valid ring was not reused"
after=$(sha256sum "$credential" | awk '{print $1}')
[[ $before == "$after" ]] || fail "valid ring was regenerated"

# Existing malformed material fails closed, exposes only a validation class, and
# is left byte-for-byte intact for explicit operator remediation.
printf '%s' '{"keys":{"1":"bad"}}' > "$credential"
cp "$credential" "$TMPROOT/malformed-before"
out=$( (ensure_application_secret_keyring "$TMPROOT/release") 2>&1 ) && fail "malformed ring was accepted"
grep -q 'invalid_key_encoding' <<<"$out" || fail "malformed ring reason was not actionable"
cmp -s "$credential" "$TMPROOT/malformed-before" || fail "malformed ring was overwritten"

grep -q '^LoadCredential=application-secret-kek-ring:' "$ROOT/deploy/systemd/fire-backend.service" \
    || fail "web service does not load the provisioned application-secret credential"

if [[ $failures -eq 0 ]]; then
    echo "ok: application-secret KEK ring provisioning is runtime-compatible and idempotent"
else
    exit 1
fi
