# Generated by Django 5.2.16 on 2026-08-07 19:06

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("organizations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DepartmentMembership",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("DEPARTMENT_ADMIN", "Department administrator")],
                        default="DEPARTMENT_ADMIN",
                        max_length=32,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_department_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="memberships",
                        to="organizations.department",
                    ),
                ),
                (
                    "revoked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="revoked_department_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="department_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("active", True)),
                        fields=("user", "department", "role"),
                        name="one_active_department_role",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("role", "DEPARTMENT_ADMIN")),
                        name="membership_role_is_department_admin",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("active", True),
                                ("revoked_at__isnull", True),
                                ("revoked_by__isnull", True),
                            ),
                            models.Q(
                                ("active", False),
                                ("revoked_at__isnull", False),
                                ("revoked_by__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        name="department_membership_revocation_state",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="StationAdminAssignment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_station_admin_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "revoked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="revoked_station_admin_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="admin_assignments",
                        to="organizations.station",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="station_admin_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("active", True)),
                        fields=("user", "station"),
                        name="one_active_station_admin_assignment",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("active", True),
                                ("revoked_at__isnull", True),
                                ("revoked_by__isnull", True),
                            ),
                            models.Q(
                                ("active", False),
                                ("revoked_at__isnull", False),
                                ("revoked_by__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        name="station_assignment_revocation_state",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SystemRole",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("SYSTEM_ADMIN", "System administrator")],
                        default="SYSTEM_ADMIN",
                        max_length=32,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_system_roles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="system_roles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("active", True)),
                        fields=("user", "role"),
                        name="one_active_system_role",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("role", "SYSTEM_ADMIN")),
                        name="system_role_is_system_admin",
                    ),
                ],
            },
        ),
    ]
