# Generated by Django 5.1.2 on 2026-08-25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("organizations", "0006_department_tablet_asset_number_policy")]

    operations = [
        migrations.AddField(
            model_name="department",
            name="locale",
            field=models.CharField(
                choices=[
                    ("de-DE", "Deutsch (Deutschland)"),
                    ("de-AT", "Deutsch (Österreich)"),
                    ("de-CH", "Deutsch (Schweiz)"),
                    ("en-GB", "English (United Kingdom)"),
                    ("fr-FR", "Français (France)"),
                    ("it-IT", "Italiano (Italia)"),
                    ("nl-NL", "Nederlands (Nederland)"),
                    ("pl-PL", "Polski (Polska)"),
                    ("cs-CZ", "Čeština (Česko)"),
                    ("sk-SK", "Slovenčina (Slovensko)"),
                    ("hu-HU", "Magyar (Magyarország)"),
                    ("da-DK", "Dansk (Danmark)"),
                    ("sv-SE", "Svenska (Sverige)"),
                    ("nb-NO", "Norsk bokmål (Norge)"),
                    ("fi-FI", "Suomi (Suomi)"),
                    ("es-ES", "Español (España)"),
                    ("pt-PT", "Português (Portugal)"),
                ],
                default="de-DE",
                max_length=8,
            ),
        ),
        migrations.AddField(
            model_name="department",
            name="timezone",
            field=models.CharField(
                choices=[
                    ("Europe/Berlin", "Europe/Berlin"),
                    ("Europe/Vienna", "Europe/Vienna"),
                    ("Europe/Zurich", "Europe/Zurich"),
                    ("Europe/Paris", "Europe/Paris"),
                    ("Europe/Amsterdam", "Europe/Amsterdam"),
                    ("Europe/Brussels", "Europe/Brussels"),
                    ("Europe/Luxembourg", "Europe/Luxembourg"),
                    ("Europe/Rome", "Europe/Rome"),
                    ("Europe/Madrid", "Europe/Madrid"),
                    ("Europe/Lisbon", "Europe/Lisbon"),
                    ("Europe/London", "Europe/London"),
                    ("Europe/Dublin", "Europe/Dublin"),
                    ("Europe/Copenhagen", "Europe/Copenhagen"),
                    ("Europe/Stockholm", "Europe/Stockholm"),
                    ("Europe/Oslo", "Europe/Oslo"),
                    ("Europe/Helsinki", "Europe/Helsinki"),
                    ("Europe/Warsaw", "Europe/Warsaw"),
                    ("Europe/Prague", "Europe/Prague"),
                    ("Europe/Bratislava", "Europe/Bratislava"),
                    ("Europe/Budapest", "Europe/Budapest"),
                    ("Europe/Ljubljana", "Europe/Ljubljana"),
                    ("Europe/Zagreb", "Europe/Zagreb"),
                    ("Europe/Sarajevo", "Europe/Sarajevo"),
                    ("Europe/Belgrade", "Europe/Belgrade"),
                    ("Europe/Sofia", "Europe/Sofia"),
                    ("Europe/Bucharest", "Europe/Bucharest"),
                    ("Europe/Athens", "Europe/Athens"),
                    ("Europe/Tallinn", "Europe/Tallinn"),
                    ("Europe/Riga", "Europe/Riga"),
                    ("Europe/Vilnius", "Europe/Vilnius"),
                ],
                default="Europe/Berlin",
                max_length=64,
            ),
        ),
    ]
